[project]
authors = ["Brian-M-J <brianmj02@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "par_comb"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "*"
